### ISSUE TITLE
Question on "Rackspace::RackConnect::PoolNode" and RackConnect v2

### ISSUE THREAD

**Issue by patrickmslatteryvt** [rackerlabs/heat-ci#15]
Hi, I was wondering if the "Rackspace::RackConnect::PoolNode" object used in:
https://github.com/rackerlabs/heat-ci/blob/master/dev/rackconnect.template
is specific to RackConnect v3 or if it can be used to connect to the pools of an F5 BigIP setup with an account that is currently setup with RackConnect v2?
Thanks

**Comment by chrishultin** [comment]
Hello Patrick,

Unfortunately, we don't have an API for interacting with RackConnect v2, so we are unable to interact with it in such a way.  The Rackspace::RackConnect::* resources are only compatible with RackConnect v3.

-Chris Hultin
